# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6ca249004ea882359d298e966990f810758a90967574a8a0456dd622f0fddaf97eb0ca1ef30a904745fa527e205c6d5a3f1a71e14fcdb5d68905cfe59f1bb1d

test:
  secret_key_base: d42d5a943c8461a88e81678b18d37550d2859c2174a8162dd3c3c5dbda911f5a63585f95f344b6038cafe12aa904ae2993020a0e7fc1b4b8166b5ec042fb68b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
